-- Nested Hyprland for testing Bifrost in "nested" run mode (scripts/nested.sh).
-- Runs as a window on the real desktop with its own D-Bus session, so Bifrost
-- can own notifications, the session lock and polkit without touching the
-- production shell. This file is only used by the nested instance.

local repo = os.getenv("BIFROST_REPO") or (os.getenv("HOME") .. "/.local/share/bifrost-shell")
local qs = "qs ipc -p " .. repo .. "/shell call "

hl.config({ autogenerated = false })

hl.monitor({ output = "", mode = "1720x1000", position = "0x0", scale = 1 })

hl.config({
	input = { kb_layout = "se", follow_mouse = 1 },
	general = { gaps_in = 6, gaps_out = 12, border_size = 1, layout = "dwindle" },
	decoration = {
		rounding = 10,
		blur = { enabled = true, size = 3, passes = 2, noise = 0.0, contrast = 1.0, brightness = 1.0, vibrancy = 0.0 },
	},
	misc = { disable_hyprland_logo = true, disable_splash_rendering = true },
})

hl.on("hyprland.start", function()
	hl.exec_cmd("env BIFROST_RUN_MODE=nested qs -n -p " .. repo .. "/shell")
	hl.exec_cmd("kitty")
end)

-- The host Hyprland handles its own SUPER bindings first (e.g. SUPER+L), so the
-- nested instance uses modifiers the host leaves free: SUPER+ALT+SHIFT (and
-- SUPER+CTRL+ALT to move windows).
local mod = "SUPER + ALT + SHIFT"
local moveMod = "SUPER + CTRL + ALT"

hl.bind(mod .. " + T", hl.dsp.exec_cmd("kitty"))
hl.bind(mod .. " + space", hl.dsp.exec_cmd(qs .. "launcher toggle"))
hl.bind(mod .. " + N", hl.dsp.exec_cmd(qs .. "notifications toggle"))
hl.bind(mod .. " + L", hl.dsp.exec_cmd(qs .. "lock lock"))
hl.bind(mod .. " + X", hl.dsp.exec_cmd(qs .. "power toggle"))
hl.bind(mod .. " + Q", hl.dsp.window.close())
hl.bind(mod .. " + E", hl.dsp.exit())
for i = 1, 5 do
	hl.bind(mod .. " + " .. i, hl.dsp.focus({ workspace = tostring(i) }))
	hl.bind(moveMod .. " + " .. i, hl.dsp.window.move({ workspace = tostring(i) }))
end
