-- Auto-generated by DMS — do not edit manually

hl.monitor({ output = "", mode = "preferred", position = "0x0", scale = 1 })
hl.monitor({ output = "DP-2", mode = "5120x1440@239.761", position = "0x0", scale = 1, vrr = 0, bitdepth = 10 })
