-- Bifrost login screen: the minimal Hyprland session greetd starts for the
-- greeter (greeter/bin/bifrost-greeter). No shortcuts, no animations, no
-- other programs: only the login screen. The keyboard layout and displays
-- come from the copy of your settings (`bifrostctl greeter sync`); without it
-- Hyprland's defaults apply.

local root = os.getenv("BIFROST_GREETER_ROOT") or "/usr/share/bifrost-greeter"
local cache = os.getenv("BIFROST_GREETER_CACHE") or "/var/cache/bifrost-greeter"

hl.config({ autogenerated = false })

hl.config({
	misc = {
		disable_hyprland_logo = true,
		disable_splash_rendering = true,
		key_press_enables_dpms = true,
		mouse_move_enables_dpms = true,
	},
	animations = { enabled = false },
	decoration = { shadow = { enabled = false } },
})

-- A missing or broken copy must never stop the login screen.
local f = io.open(cache .. "/hypr/local.lua", "r")
if f then
	f:close()
	pcall(dofile, cache .. "/hypr/local.lua")
end

-- Testing: an extra file (e.g. a fixed monitor size for the nested test).
local extra = os.getenv("BIFROST_GREETER_HYPR_EXTRA")
if extra and extra ~= "" then
	pcall(dofile, extra)
end

hl.on("hyprland.start", function()
	hl.exec_cmd(root .. "/greeter/session.sh")
end)
