-- Auto-generated by DMS Matugen hook — do not edit manually.
-- Remove require("dms.colors") from hyprland.lua to override.

hl.config({
	general = {
		col = {
			active_border = "rgb(7daea3)",
			inactive_border = "rgb(a89984)",
		},
	},
	group = {
		col = {
			border_active = "rgb(7daea3)",
			border_inactive = "rgb(a89984)",
			border_locked_active = "rgb(ea6962)",
			border_locked_inactive = "rgb(a89984)",
		},
		groupbar = {
			col = {
				active = "rgb(7daea3)",
				inactive = "rgb(a89984)",
				locked_active = "rgb(ea6962)",
				locked_inactive = "rgb(a89984)",
			},
		},
	},
})
